def test_func2():
    raise Exception("asdf")
