def pytest_runtest_setup():
    raise Exception("2")
